### ISSUE TITLE
I see a error in replit

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [Gooodgis/dont-touch-my-presents#1]
Screenshot :-

![Screenshot_20230120-132139](https://user-images.githubusercontent.com/109818645/213644474-30fc95ae-185d-4247-835c-ddbb669f7371.png)

Website :- www.replit.com

**Comment by Gooodgis** [comment]
Maybe this is just an issue with replit? Does the game run on your computer?

**Comment by hexatorum** [comment]
> Maybe this is just an issue with replit?
i worked with replit a bit and i am pretty sure this is an issue with the repl template

from what i understand so far, graphics programs on replit run in an x11 environment, which the python 3 template does not have
choose the pygame template instead and it'll work

**Comment by Gooodgis** [comment]
Thanks @kingofsponges 

Closing this issue
